"""create new table unsubscriber

Revision ID: 316d8a7163b
Revises: 853651b71a
Create Date: 2015-06-19 17:43:55.559349

"""

# revision identifiers, used by Alembic.
revision = '316d8a7163b'
down_revision = '853651b71a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unsubscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('list_id', sa.Unicode(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_unsub', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unsubscriber')
    ### end Alembic commands ###
